#!/usr/bin/env python3
"""Run the SDL UI screenshot lane across desktop HUD sizes and build a contact sheet."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "build" / "tileset-hud-review"
DEFAULT_SIZES = [
    (840, 800),
    (1074, 827),
    (1280, 720),
    (1440, 900),
]
HUD_FRAMES = [
    "02-isometric-overview.bmp",
    "03-selected-peasant.bmp",
    "03f-selected-peasant-hover-action.bmp",
    "04-build-menu.bmp",
    "04a-build-menu-hover-card.bmp",
    "05-selected-townhall-diagnostics.bmp",
    "07-after-60-ticks.bmp",
    "10-top-right-isometric.bmp",
    "12-bottom-right-isometric.bmp",
    "15-night-torch-light.bmp",
]


@dataclass(frozen=True)
class ReviewRun:
    width: int
    height: int

    @property
    def slug(self) -> str:
        return f"{self.width}x{self.height}"


def parse_size(value: str) -> tuple[int, int]:
    if "x" not in value.lower():
        raise argparse.ArgumentTypeError("Use WIDTHxHEIGHT, for example 1280x720")
    raw_w, raw_h = value.lower().split("x", 1)
    try:
        width = int(raw_w)
        height = int(raw_h)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("Width and height must be integers") from exc
    if width < 640 or height < 420:
        raise argparse.ArgumentTypeError("Size is too small for the desktop HUD review")
    return width, height


def realm_exe() -> Path:
    exe = ROOT / "bin" / "realm.exe"
    if not exe.exists():
        raise FileNotFoundError(f"Missing {exe}; build first with mingw32-make gfx")
    return exe


def run_capture(review: ReviewRun, out_dir: Path) -> None:
    env = os.environ.copy()
    env.update(
        {
            "REALM_UI_TEST": "1",
            "REALM_UI_TEST_WIDTH": str(review.width),
            "REALM_UI_TEST_HEIGHT": str(review.height),
            "REALM_UI_TEST_DIR": str(out_dir),
            "REALM_UI_TEST_ZOOM": env.get("REALM_UI_TEST_ZOOM", "20"),
        }
    )
    subprocess.run([str(realm_exe())], cwd=ROOT, env=env, check=True)


def load_pillow():
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError as exc:
        raise SystemExit(
            "Pillow is required for the contact sheet. Install it or rerun with --no-contact-sheet."
        ) from exc
    return Image, ImageDraw, ImageFont


def make_contact_sheet(runs: list[ReviewRun], out_root: Path) -> Path:
    Image, ImageDraw, ImageFont = load_pillow()
    thumb_w = 240
    pad = 12
    label_h = 40
    title_h = 44
    cols = len(runs)
    rows = len(HUD_FRAMES)
    sheet_w = pad + cols * (thumb_w + pad)
    sheet_h = title_h + pad + rows * (label_h + 170 + pad)
    sheet = Image.new("RGB", (sheet_w, sheet_h), (18, 19, 22))
    draw = ImageDraw.Draw(sheet)
    font = ImageFont.load_default()

    draw.text((pad, 14), "Tileset HUD review", fill=(235, 237, 232), font=font)
    for col, run in enumerate(runs):
        x = pad + col * (thumb_w + pad)
        draw.text((x, title_h), run.slug, fill=(205, 210, 214), font=font)

    for row, frame in enumerate(HUD_FRAMES):
        y = title_h + pad + row * (label_h + 170 + pad)
        draw.text((pad, y + 16), frame, fill=(165, 171, 176), font=font)
        for col, run in enumerate(runs):
            x = pad + col * (thumb_w + pad)
            src = out_root / run.slug / frame
            if not src.exists():
                draw.rectangle((x, y + label_h, x + thumb_w, y + label_h + 160), fill=(40, 22, 26))
                draw.text((x + 8, y + label_h + 70), "missing", fill=(245, 110, 120), font=font)
                continue
            img = Image.open(src).convert("RGB")
            ratio = min(thumb_w / img.width, 160 / img.height)
            tw = max(1, int(img.width * ratio))
            th = max(1, int(img.height * ratio))
            thumb = img.resize((tw, th), Image.Resampling.LANCZOS)
            bg = Image.new("RGB", (thumb_w, 160), (8, 9, 12))
            bg.paste(thumb, ((thumb_w - tw) // 2, (160 - th) // 2))
            sheet.paste(bg, (x, y + label_h))

    path = out_root / "contact-sheet.png"
    sheet.save(path)
    return path


def write_report(runs: list[ReviewRun], out_root: Path, contact_sheet: Path | None) -> Path:
    lines = [
        "# Tileset HUD visual review",
        "",
        "Generated by `scripts/review_tileset_hud.py`.",
        "",
        "## Sizes",
    ]
    for run in runs:
        lines.append(f"- `{run.slug}`: `{out_root / run.slug}`")
    lines.extend(["", "## Frames"])
    for frame in HUD_FRAMES:
        lines.append(f"- `{frame}`")
    if contact_sheet:
        lines.extend(["", f"Contact sheet: `{contact_sheet}`"])
    path = out_root / "report.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--size",
        action="append",
        type=parse_size,
        help="Desktop review size as WIDTHxHEIGHT. May be repeated.",
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--no-run", action="store_true", help="Only rebuild report/contact sheet from existing captures.")
    parser.add_argument("--no-clean", action="store_true", help="Do not delete the previous review output first.")
    parser.add_argument("--no-contact-sheet", action="store_true")
    args = parser.parse_args(argv)

    runs = [ReviewRun(w, h) for w, h in (args.size or DEFAULT_SIZES)]
    out_root = args.out.resolve()
    if not args.no_run and out_root.exists() and not args.no_clean:
        shutil.rmtree(out_root)
    out_root.mkdir(parents=True, exist_ok=True)

    if not args.no_run:
        for run in runs:
            run_dir = out_root / run.slug
            run_dir.mkdir(parents=True, exist_ok=True)
            print(f"realm hud review: capture {run.slug} -> {run_dir}", flush=True)
            run_capture(run, run_dir)

    contact_sheet = None
    if not args.no_contact_sheet:
        contact_sheet = make_contact_sheet(runs, out_root)
        print(f"realm hud review: contact sheet {contact_sheet}", flush=True)
    report = write_report(runs, out_root, contact_sheet)
    print(f"realm hud review: report {report}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
